site_name: sthali-core
site_url: https://project-sthali.github.io/sthali-core/
site_description: A core package for Sthali development
site_author: Jhunu Fernandes
repo_url: https://github.com/project-sthali/sthali-core/
repo_name: sthali-core
nav:
  - Home: index.md
  - Requirements: requirements.md
  - Installation: installation.md
  - Usage: usage.md
  - About:
    - License: license.md
    - Release Notes: https://github.com/project-sthali/sthali-core/releases
    - Issue Tracker: https://github.com/project-sthali/sthali-core/issues
  - API Reference:
theme: readthedocs