name: deploy
on:
  push:
    branches:
      - main
jobs:
  run-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: |
          python -m venv .venv
          .venv/bin/python -m pip install --upgrade pip
          .venv/bin/python -m pip install .[stage]
      - run: |
          .venv/bin/python -m build -o ./dist
      - uses: pypa/gh-action-pypi-publish@release/v1
