name: deps
on:
  workflow_call:
    inputs:
      pip_args:
        required: true
        type: string
jobs:
  install-python-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - uses: actions/cache@v4
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          .venv/bin/python -m pip install --upgrade pip
          .venv/bin/python -m pip install .[${{ inputs.pip_args }}]
      - run: |
          zip -r venv.zip .venv
      - uses: actions/upload-artifact@v4
        with:
          name: python-deps-${{ inputs.pip_args }}
          path: venv.zip
