name: docs
on:
  push:
    branches:
      - main
jobs:
  install-deps:
    uses: project-sthali/sthali-core/.github/workflows/deps.yml@main
    with:
      pip_args: stage
  build-docs:
    needs:
      - install-deps
    if: github.event.head_commit.message != 'Automated docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: python-deps-stage
          path: .
      - run: |
          unzip venv.zip
      - run: |
          .venv/bin/python -m sthali_core generate docs
      - run: |
          git config --global user.name 'jhunu.fernandes'
          git config --global user.email 'jhunu.fernandes@gmail.com'
      - run: |
          git add docs/
          if ! git diff --cached --quiet; then
            git commit -am "Automated docs"
            git push
          fi
  deploy-docs:
    needs:
      - build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: python-deps-stage
          path: .
      - run: |
          .venv/bin/python -m mkdocs gh-deploy -f docs/mkdocs.yml
