name: install python deps
on:
  workflow_call:
    inputs:
      extras:
        required: true
        type: string
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: venv
        run: |
          python -m venv .venv
      - name: upgrade pip
        run: |
          .venv/bin/python -m pip install --upgrade pip
      - name: pip install
        run: |
          .venv/bin/python -m pip install .[${{ inputs.extras }}]
      - name: zip venv
        run: |
          zip -r venv.zip .venv
      - uses: actions/upload-artifact@v4
        with:
          name: python-deps-${{ inputs.extras }}
          path: venv.zip
