name: run-deploy
on:
  # workflow_call
  workflow_run:
    workflows:
      - tests
    branches:
      - main
    types:
      - completed
jobs:
  install-deps:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: project-sthali/sthali-core/.github/workflows/install-python-deps.yml@main
    with:
      extras: stage
  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: python-deps-stage
          path: .
      - name: unpack venv
        run: |
          unzip venv.zip
      - name: build
        run: |
          .venv/bin/python -m build -o ./dist
      - uses: pypa/gh-action-pypi-publish@release/v1
  gh-pages-deploy:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: python-deps-stage
          path: .
      - name: unpack venv
        run: |
          unzip venv.zip
      - name: mkdocs gh-deploy
        run: |
          .venv/bin/python -m mkdocs gh-deploy -f docs/mkdocs.yml
