name: tests
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
jobs:
  install-deps:
    uses: project-sthali/sthali-core/.github/workflows/deps.yml@develop
    with:
      pip_args: tests
  run-tests:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - uses: actions/download-artifact@v4
        with:
          name: python-deps-tests
          path: .
      - run: |
          unzip venv.zip
      - run: |
          .venv/bin/python -m unittest discover -v
