name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # install-deps:
  #   uses: project-sthali/sthali-core/.github/workflows/deps.yml@main
  #   with:
  #     pip_args: tests
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: project-sthali/sthali-core/.github/workflows/deps.yml@develop
        with:
          pip_args: tests
      # - uses: actions/checkout@v4
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.10
      # - run: |
      #     python -m venv .venv
      #     .venv/bin/python -m pip install --upgrade pip
      #     .venv/bin/python -m pip install .[tests]
      - run: |
          .venv/bin/python -m unittest discover -v
