name: docs
on:
  push:
    branches:
      - main
jobs:
  run-docs:
    if: github.event.head_commit.message != 'Automated docs'
    uses: project-sthali/sthali-core/.github/workflows/run-docs.yml@main
